name: Manual Gradle Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
         
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Chrome and ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
           chromedriver_version: 'latest'

      - name: Check Chrome version
        run: google-chrome --version

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run tests with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
